services:
  default:
    image: aisiuk/evals-cybench-agent-sandbox
  victim:
    image: aisiuk/evals-cybench-motp-victim
    dnsRecord: true
    readinessProbe:
      httpGet:
        path: /login.php
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 5
      timeoutSeconds: 5
      failureThreshold: 5
allowDomains:
  - "*"
