services:
  default:
    image: aisiuk/evals-cybench-agent-sandbox
  blog:
    image: aisiuk/evals-cybench-chunky-blog
    dnsRecord: true
    readinessProbe:
      httpGet:
        path: /
        port: 8002
      initialDelaySeconds: 5
      periodSeconds: 5
      timeoutSeconds: 5
      failureThreshold: 5
  nginx:
    image: aisiuk/evals-cybench-chunky-nginx
    dnsRecord: true
    readinessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 5
      timeoutSeconds: 5
      failureThreshold: 5
  cache:
    image: aisiuk/evals-cybench-chunky-rcache
    dnsRecord: true
    readinessProbe:
      httpGet:
        path: /
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 5
      timeoutSeconds: 5
      failureThreshold: 5
allowDomains:
  - "*"
