services:
  default:
    # NOTE: Using the default runtime (gvisor) results in an error:
    # `subprocess.SubprocessError: Exception occurred in preexec_fn` when running the
    # solution.sh script.
    runtimeClassName: runc
    image: aisiuk/evals-cybench-agent-sandbox
allowDomains:
  - "*"
