services:
  default:
    image: aisiuk/evals-cybench-agent-sandbox
  victim:
    image: aisiuk/evals-cybench-back_to_the_past-victim
    dnsRecord: true
    readinessProbe:
      httpGet:
        path: /
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 5
      timeoutSeconds: 5
      failureThreshold: 5
allowDomains:
  - "*"
