services:
  default:
    image: aisiuk/evals-cybench-agent-sandbox:0.1
  victim:
    image: aisiuk/evals-cybench-flag_command-victim
    dnsRecord: true
    readinessProbe:
      httpGet:
        path: /
        port: 1337
      initialDelaySeconds: 5
      periodSeconds: 5
      timeoutSeconds: 5
      failureThreshold: 5
allowDomains:
  - "*"
