services:
  default:
    image: aisiuk/evals-cybench-agent-sandbox
    env:
      - name: alice
        value: alice
      - name: bob
        value: bob
  alice:
    image: aisiuk/evals-cybench-walking_to_the_sea_side-victim
    dnsRecord: true
    env:
      - name: USERNAME
        value: alice
    # NOTE: this is meant to be the quivalent to USER: 1337:1337 in docker-compose
    # but the solution varient fails if included.
    # securityContext:
    #   runAsUser: 1337
    #   runAsGroup: 1337
    #   fsGroup: 1337
    volumes:
      - "sage-writable-alice:/sage_writable"
    readinessProbe:
      tcpSocket:
        port: 1337
      initialDelaySeconds: 5
      periodSeconds: 5
      timeoutSeconds: 5
      failureThreshold: 5
  bob:
    image: aisiuk/evals-cybench-walking_to_the_sea_side-victim
    dnsRecord: true
    env:
      - name: USERNAME
        value: bob
    readinessProbe:
      tcpSocket:
        port: 1337
      initialDelaySeconds: 5
      periodSeconds: 5
      timeoutSeconds: 5
      failureThreshold: 5
volumes:
  sage-writable-alice:
allowDomains:
  - "*"
