services:
  default:
    image: aisiuk/evals-cybench-agent-sandbox
  victim:
    image: aisiuk/evals-cybench-noisy_crc-victim
    dnsRecord: true
    readinessProbe:
      tcpSocket:
        port: 9999
      initialDelaySeconds: 5
      periodSeconds: 5
      timeoutSeconds: 5
      failureThreshold: 5
allowDomains:
  - "*"
